### ISSUE TITLE
Move `publish` hooks to `version`, add more publishing automation

### ISSUE THREAD

**Issue by UltCombo** [JSRocksHQ/slush-es20xx#31]
- `preversion`: git pull, update deps (babel-core, runtime with `--save-exact` #30), run tests
- `postversion`: git push, git push --tag, npm publish

**Comment by UltCombo** [comment]
Must also add a note to the docs that this requires `npm@>=2.11`. Adding `npm i -g npm` to the install instructions may be a good idea.

**Comment by UltCombo** [comment]
Updating the runtime with `--save-exact` will a generate a diff, thus making `npm version` fail as the working directory will not be clean anymore.

I'd rather avoid generating more implicit commits, and I don't want to duplicate `npm version`'s clean checking logic.

Though, having `npm version` fail due to not already having up to date dependencies, when `preversion` is supposed to update those dependencies, is rather contradictory and confusing at best.

Perhaps adding some more implicit magic would provide a better user experience then.

**Comment by UltCombo** [comment]
So, to be clear, I'm planning to update the babel-runtime and commit the `package.json` as part of the `preversion` script.

This may lead to unexpected changes being implicitly committed if the `package.json` was already dirty before running `npm version`. Still, I'd rather avoid duplicating the clean checking logic.

Need to decide whether we should allow this side-effect or duplicate the clean working tree checking logic.

**Comment by UltCombo** [comment]
I'm splitting the `preversion` script into sub scripts in order to make the code more readable and reusable. These sub scripts can even be run standalone, and this is also very useful for end-users -- e.g. one can `npm run update-babel` whenever wanted, not just as part of the `preversion` script.

I've gave a lot of thought to the clean working tree and implicit commit topics.

Turns out it is not very hard to check for a clean working tree using [Git's plumbing commands](https://www.kernel.org/pub/software/scm/git/docs/#_low_level_commands_plumbing), and the benefits in this case seem worth the effort.

Implicit commits are intrusive, and should be avoided. This means implicit commits will only be performed when absolutely necessary.

`npm run update-babel` by itself will not generate an implicit commit. However, as part of the `preversion` script, if the `package.json` has been modified due to the `update-babel` script, then it will be implicitly committed in order to not fail the `npm version` command. Note that the `preversion` script will fail earlier if there are any uncommitted changes in the repository, so there should be no need to check whether the `package.json` is clean at this point.

**Comment by UltCombo** [comment]
We now have new [sample code](https://github.com/JSRocksHQ/slush-es20xx/blob/master/tpl/env/node/src/index.js) and a new [deployment automation](https://github.com/JSRocksHQ/slush-es20xx#deploying).

@jaydson can you test/review these in the master branch before we apply it to Harmonic? Feel free to give suggestions as well. :smile:

**Comment by jaydson** [comment]
wow, i'll review!

**Comment by jaydson** [comment]
Awesome job @UltCombo !
We can apply it in Harmonic.
